name: make snap tracker

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@master

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@master
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install --force
        npm run make

    - name: Get version
      id: version
      run: echo "::set-output name=version::$(cat package.json | jq -r '.version')"

    - name: Release
      uses: softprops/action-gh-release@master
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: /home/runner/work/marvelsnaptracker/marvelsnaptracker/out/make/zip/linux/x64/Marvel Snap Tracker-linux-x64-${{ steps.version.outputs.version }}.zip
